sort: alloc.c main.c parselines.c ../5-6/getline.c 5-7_main.c 5-7_parselines.c qsort.c
	gcc -o sort_alloc -Wall qsort.c alloc.c main.c parselines.c ../5-6/getline.c
	gcc -o sort_array -Wall qsort.c 5-7_main.c 5-7_parselines.c ../5-6/getline.c
